// @ts-nocheck
/* zoo_svelte_state.svelte.ts generated by Svelte v5.28.2 */
import * as $ from 'svelte/internal/client';
/**
 * Svelte-idiomatic zoo implementation.
 * Uses Svelte 5 $state runes for reactivity.
 */
import {random_float, random_int} from '@ryanatkn/belt/random.js';
import {create_random_alea} from '@ryanatkn/belt/random_alea.js';
import {transform_points} from '$lib/point_helpers.js';
import {compute_unit_color} from '$lib/unit_logic.js';
import {colors_default} from '$lib/renderer.svelte.js';
import {Collisions} from '$lib/collisions.js';
import {colliding} from '$lib/colliding.js';
import {cr} from '$lib/collision_result.js';
import {physics_apply_bounce} from '$lib/physics.js';
import {SPEED_DEFAULT} from '$lib/unit_types.js';

/**
 * Zoo agent - a simple entity in the zoo.
 * Uses Svelte 5 $state for reactive properties.
 */
export class Zoo_Agent {
	// Identity
	id;
	#dead = $.state(false);

	get dead() {
		return $.get(this.#dead);
	}

	set dead(value) {
		$.set(this.#dead, value, true);
	}

	type;
	#x = $.state(0);
	#y = $.state(0);
	rotation;
	scale;

	get x() {
		return $.get(this.#x);
	}

	set x(v) {
		$.set(this.#x, v, true);
		if (this.body) this.body.x = v;
	}

	get y() {
		return $.get(this.#y);
	}

	set y(v) {
		$.set(this.#y, v, true);
		if (this.body) this.body.y = v;
	}

	// Movement
	speed;
	#direction_x = $.state(0);

	get direction_x() {
		return $.get(this.#direction_x);
	}

	set direction_x(value) {
		$.set(this.#direction_x, value, true);
	}

	#direction_y = $.state(0);

	get direction_y() {
		return $.get(this.#direction_y);
	}

	set direction_y(value) {
		$.set(this.#direction_y, value, true);
	}

	// Shape (circle)
	radius;
	// Shape (polygon)
	points;
	transformed_points;
	// Derived
	color;
	// Collision body (managed externally)
	body;

	constructor(
		id,
		type,
		x,
		y,
		radius,
		points,
		rotation,
		scale,
		speed,
		direction_x,
		direction_y,
		colors,
	) {
		this.id = id;
		this.type = type;
		$.set(this.#x, x, true);
		$.set(this.#y, y, true);
		this.radius = radius;
		this.points = points;
		this.rotation = rotation;
		this.scale = scale;
		this.speed = speed;
		this.direction_x = direction_x;
		this.direction_y = direction_y;
		// Pre-compute transformed points for polygons
		this.transformed_points = type === 'polygon' ? transform_points(points, rotation, scale) : [];
		// Compute color once (won't change in this demo)
		this.color = compute_unit_color(false, type, true, false, [], colors);
	}
}

const BOUNDS_SIZE = 100000;

/**
 * Zoo state manager - owns agents and simulation.
 */
export class Zoo_State {
	#width = $.state(800);

	get width() {
		return $.get(this.#width);
	}

	set width(value) {
		$.set(this.#width, value, true);
	}

	#height = $.state(600);

	get height() {
		return $.get(this.#height);
	}

	set height(value) {
		$.set(this.#height, value, true);
	}

	#agent_count = $.state(72);

	get agent_count() {
		return $.get(this.#agent_count);
	}

	set agent_count(value) {
		$.set(this.#agent_count, value, true);
	}

	#agent_scale = $.state(1);

	get agent_scale() {
		return $.get(this.#agent_scale);
	}

	set agent_scale(value) {
		$.set(this.#agent_scale, value, true);
	}

	#simulation_speed = $.state(1);

	get simulation_speed() {
		return $.get(this.#simulation_speed);
	}

	set simulation_speed(value) {
		$.set(this.#simulation_speed, value, true);
	}

	#agents = $.state($.proxy([]));

	get agents() {
		return $.get(this.#agents);
	}

	set agents(value) {
		$.set(this.#agents, value, true);
	}

	#running = $.state(true);

	get running() {
		return $.get(this.#running);
	}

	set running(value) {
		$.set(this.#running, value, true);
	}

	// Colors
	colors = colors_default;
	// Collision system
	collisions = new Collisions();
	// Timing
	#frame_id = null;
	#last_time = null;
	#frame_count = $.state(0);

	get frame_count() {
		return $.get(this.#frame_count);
	}

	set frame_count(value) {
		$.set(this.#frame_count, value, true);
	}

	#fps = $.state(0);

	get fps() {
		return $.get(this.#fps);
	}

	set fps(value) {
		$.set(this.#fps, value, true);
	}

	#fps_total = 0;

	constructor(options = {}) {
		this.width = options.width ?? 800;
		this.height = options.height ?? 600;
		this.agent_count = options.agent_count ?? 72;
		this.agent_scale = options.agent_scale ?? 1;
		this.simulation_speed = options.simulation_speed ?? 1;
	}

	/**
	 * Initialize agents and start simulation.
	 */
	init() {
		this.create_agents();
		this.start();
	}

	/**
	 * Create agents based on current settings.
	 */
	create_agents() {
		// Clear existing
		this.agents = [];
		this.collisions = new Collisions();

		const random_alea = create_random_alea(this.agent_count, this.agent_scale);
		const random = (min, max) => random_float(min, max, random_alea);

		// Create boundary walls
		this.#create_bounds();

		// Create agents
		const size = 5;

		for (let i = 0; i < this.agent_count; i++) {
			const large = random_alea() > 0.5 ? i % 16 === 0 : false;
			const min_size = size * 1 * (large ? 4.2 * this.agent_scale : this.agent_scale);
			const max_size = size * 2.5 * (large ? 4.2 * this.agent_scale : this.agent_scale);
			const x = random(0, this.width);
			const y = random(0, this.height);
			const direction = (random(0, 360) * Math.PI) / 180;
			const direction_x = Math.cos(direction);
			const direction_y = Math.sin(direction);
			let agent;

			if (random_alea() > 0.7) {
				// Circle
				const radius = random(min_size, max_size);

				agent = new Zoo_Agent(
					i,
					'circle',
					x,
					y,
					radius,
					[],
					0,
					1,
					SPEED_DEFAULT * random(0.1, 1),
					direction_x,
					direction_y,
					this.colors,
				);
				agent.body = this.collisions.create_circle(x, y, radius, 1);
			} else {
				// Polygon
				let points = [
					{
						x: -random(min_size, max_size),
						y: -random(min_size, max_size),
					},
					{
						x: random(min_size, max_size),
						y: -random(min_size, max_size),
					},
					{
						x: random(min_size, max_size),
						y: random(min_size, max_size),
					},
					{
						x: -random(min_size, max_size),
						y: random(min_size, max_size),
					},
				];

				if (random_alea() > 0.17) {
					const index_to_remove = random_int(0, points.length - 1, random_alea);

					points = points.filter((_, idx) => idx !== index_to_remove);
				}

				const rotation = (random(0, 360) * Math.PI) / 180;

				agent = new Zoo_Agent(
					i,
					'polygon',
					x,
					y,
					0,
					points,
					rotation,
					1,
					SPEED_DEFAULT * random(0.1, 1),
					direction_x,
					direction_y,
					this.colors,
				);
				agent.body = this.collisions.create_polygon(x, y, points, rotation, 1, 1);
			}

			// Store back-reference
			agent.body.agent = agent;
			this.agents.push(agent);
		}
	}

	#create_bounds() {
		// Walls use clockwise winding (in screen coords) so normals point into playfield
		// Top wall
		const top = this.collisions.create_polygon(0, 0, [
			{x: 0, y: 0},
			{x: 0, y: -BOUNDS_SIZE},
			{x: this.width, y: -BOUNDS_SIZE},
			{x: this.width, y: 0},
		]);

		top.is_wall = true;

		// Right wall
		const right = this.collisions.create_polygon(0, 0, [
			{x: this.width, y: 0},
			{x: this.width + BOUNDS_SIZE, y: 0},
			{x: this.width + BOUNDS_SIZE, y: this.height},
			{x: this.width, y: this.height},
		]);

		right.is_wall = true;

		// Bottom wall
		const bottom = this.collisions.create_polygon(0, 0, [
			{x: this.width, y: this.height},
			{x: this.width, y: this.height + BOUNDS_SIZE},
			{x: 0, y: this.height + BOUNDS_SIZE},
			{x: 0, y: this.height},
		]);

		bottom.is_wall = true;

		// Left wall
		const left = this.collisions.create_polygon(0, 0, [
			{x: 0, y: this.height},
			{x: -BOUNDS_SIZE, y: this.height},
			{x: -BOUNDS_SIZE, y: 0},
			{x: 0, y: 0},
		]);

		left.is_wall = true;
	}

	/**
	 * Start the simulation loop.
	 */
	start() {
		if (this.#frame_id !== null) return;
		this.running = true;
		this.#last_time = null;
		this.#tick();
	}

	/**
	 * Stop the simulation loop.
	 */
	stop() {
		if (this.#frame_id !== null) {
			cancelAnimationFrame(this.#frame_id);
			this.#frame_id = null;
		}

		this.running = false;
	}

	/**
	 * Toggle simulation running state.
	 */
	toggle() {
		if (this.running) {
			this.stop();
		} else {
			this.start();
		}
	}

	#tick = () => {
		if (!this.running) return;

		const now = performance.now();

		if (this.#last_time !== null) {
			const dt = now - this.#last_time;

			if (dt < 1000) {
				// Skip large dt spikes
				this.#update(dt);
				// FPS tracking
				this.frame_count++;
				this.#fps_total += 1000 / dt;

				if (this.frame_count > 100) {
					this.fps = Math.round(this.#fps_total / this.frame_count);
					this.frame_count = 1;
					this.#fps_total = this.fps;
				}
			}
		}

		this.#last_time = now;
		this.#frame_id = requestAnimationFrame(this.#tick);
	};

	#update(dt) {
		const final_dt = dt * this.simulation_speed;

		// Update collision system BVH
		this.collisions.update();

		// PHASE 1: Movement
		for (const agent of this.agents) {
			if (!agent.body || agent.dead) continue;

			const unit_speed = agent.speed * final_dt;

			if (unit_speed !== 0) {
				if (agent.direction_x !== 0) {
					agent.x += agent.direction_x * unit_speed;
				}

				if (agent.direction_y !== 0) {
					agent.y += agent.direction_y * unit_speed;
				}
			}
		}

		// PHASE 2: Collision detection and response
		for (const agent of this.agents) {
			if (!agent.body) continue;

			for (const other_body of agent.body.potentials()) {
				const other_agent = other_body.agent;
				const is_wall = other_body.is_wall;

				if (colliding(agent.body, other_body, cr)) {
					if (is_wall) {
						// Bounce off wall - only move the agent, wall is immovable
						physics_apply_bounce(agent, {x: 0, y: 0, direction_x: 0, direction_y: 0}, cr, 1);
					} else if (other_agent) {
						physics_apply_bounce(agent, other_agent, cr);
					}
				}
			}
		}
	}

	/**
	 * Cleanup when destroying.
	 */
	destroy() {
		this.stop();
	}
}
